In [2]:
import numpy as np

In [7]:
myarr = np.array([3,6,32,7],np.int64)

In [12]:
myarr[1]

np.int64(6)

In [10]:
myarr.shape

(4,)

In [13]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [16]:
zeros.shape

(2, 5)

In [20]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [24]:
emp = np.empty((4,6))

In [25]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        7.56602523e-307, 4.45064851e-308, 1.20161254e-306],
       [8.45590539e-307, 2.22521103e-306, 1.06810268e-306,
        1.60219035e-306, 7.56593696e-307, 1.33511562e-306],
       [1.95812747e-306, 6.23060744e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 6.23053954e-307,
        1.78019082e-306, 1.86921279e-306, 8.34445562e-308]])

In [26]:
emp_like = np.empty_like(lspace)

In [27]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [28]:
ide = np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [30]:
ide.shape

(45, 45)

In [33]:
arr = np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr.shape()

TypeError: 'tuple' object is not callable

In [37]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.shape

(99,)

In [40]:
x = [[1,2,3],[4,5,6],[7,8,9]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
ar.sum(axis=0)

array([12, 15, 18])

In [44]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
ar.flat

In [50]:
for item in ar.flat:
 print(item)

1
2
3
4
5
6
7
8
9


In [51]:
ar.ndim

2

In [52]:
ar.size

9

In [53]:
ar.nbytes

72

In [58]:
one = np.array([1,5,543,3,4])
one

array([  1,   5, 543,   3,   4])

In [55]:
one.argmax()

np.int64(2)

In [56]:
one.argmin()

np.int64(0)

In [59]:
one.argsort()

array([0, 3, 4, 1, 2])

In [60]:
ar.argmax(axis=0)

array([2, 2, 2])

In [61]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [62]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))